-- options.lua

local options = {
    Tweaks = {
--[[		{
            item = "turboHack",
            name = "Enable PT Turbo (slightly reduce quality outdoors)",
            category = "internal",
            tooltip = "RTXDI spatial sampling is mostly needed indoors. This tweak reduces it while\noutdoors to try and maintain FPS in complex outdoor areas. It CAN reduce\nvisual quality outdoors in certain situations (white cars\nand highly reflective surfaces in particular).",
        },
        {
            item = "rainFix",
            name = "Enable PT Rain Fix",
            category = "internal",
            tooltip = "Enables full particle integration with path tracing while it's not raining\nor you're indoors." },]]
        {
            item = "DLSS_D",
            name = "Enable PT Denoiser: Ray Reconstruction",
            category = "/graphics/presets",
            tooltip = "Ultra+ allows the engine to override this avoid crashes, so this option will\nappear not to save (Default: N/A)",
        },
        {
            item = "EnableNRD",
            name = "Enable PT Denoiser: NRD",
            category = "RayTracing",
            tooltip = "NRD is only intended when NOT using ray reconstruction (for example AMD).\nThe engine tries to turn this on under certain circumstances, Ultra+ Control\nwill try and show you if it has become enabled, though there may be a bug in\nCP 2.1x that causes NRD to become partionally enabled (see the above PT21\nFPS Fix).",
        },
        {
            item = "EnableRIS",
            name = "Enable resampled importance sampling (RIS)",
            category = "RayTracing/Reference",
            tooltip = "RIS is resampled importance sampling. It is enabled by default, but disable\nit for reLIGHT.",
        },
        {
            item = "Enable",
            name = "Enable SHaRC Bounce Cache",
            category = "Editor/SHARC",
            tooltip = "(Default: On)",
        },
        {
            item = "EnableGradients",
            name = "Enable RTXDI Gradients",
            category = "Editor/RTXDI",
            tooltip = "(Default: Off)",
        },
        {
            item = "EnableSeparateDenoising",
            name = "Enable RTXDI Separate Denoising",
            category = "Editor/RTXDI",
            tooltip = "(Default: On)",
        },
    },
    Features = {
        {
            item = "Bloom",
            name = "Bloom",
            category = "Developer/FeatureToggles",
            tooltip = "(Default: On)",
        },
        {
            item = "Distortion",
            name = "Distortion Effects",
            category = "Developer/FeatureToggles",
            tooltip = "(Default: On)",
        },
        {
            item = "ScreenSpaceHeatHaze",
            name = "Heat Haze",
            category = "Developer/FeatureToggles",
            tooltip = "Can distort badly with path tracing (Default: On)",
        },
        {
            item = "VolumetricFog",
            name = "Volumetric Fog",
            category = "Developer/FeatureToggles",
            tooltip = "",
        },
        {
            item = "DistantVolFog",
            name = "Distant Volumetric Fog",
            category = "Developer/FeatureToggles",
            tooltip = "Can be less obvious depending on which weather env you're using (Default: On)",
        },
        {
            item = "DistantFog",
            name = "Distant Fog",
            category = "Developer/FeatureToggles",
            tooltip = "Makes buildings and mountains fade into the atmosphere (Default: On)",
        },
        {
            item = "DistantGI",
            name = "Distant Global Illumination",
            category = "Developer/FeatureToggles",
            tooltip = "Distant global illumination (Default: On)",
        },
        {
            item = "DistantShadows",
            name = "Distant Shadows",
            category = "Developer/FeatureToggles",
            tooltip = "(Default: On)",
        },
        {
            item = "HideFPPAvatar",
            name = "Hide player in reflections (except for head)",
            category = "RayTracing",
            tooltip = "Because why would we want the head? (Default: Off)",
        },
        {
            item = "CharacterRimEnhancement",
            name = "Object (and character) rim enhancement",
            category = "Developer/FeatureToggles",
            tooltip = "Only works in raster and RT modes (Default: On)",
        },
        {
            item = "EnableCustomMipBias",
            name = "Force INI Mip Bias",
            category = "Editor/MipBias",
            tooltip = "Caution: Not recommended for 12GB VRAM or less (Default: Off)",
        },
    },
    

    RTXDI = {
        {
            item = "EnableLocalLightImportanceSampling",
            name = "Local-Light Importance Sampling (LLIS)",
            category = "Editor/RTXDI",
            tooltip = "Prioritise Local Light sources when sampling the image, implementation appears problematic",
        },
        {
            item = "EnableFallbackLight",
            name = "Fallback Lighting",
            category = "Editor/RTXDI",
            tooltip = "Use a fallback light when sampling is insufficient, may introduce bias but aids with LLIS",
        },
        {
            item = "EnableApproximateTargetPDF",
            name = "Approximate Target PDF",
            category = "Editor/RTXDI",
            tooltip = "Unknown impact, found it reduced performance for no reasonable quality gain",
        },
        {
            item = "UseFusedApproach",
            name = "Enable Fused Spatiotemporal DI",
            category = "Editor/RTXDI",
            tooltip = "Perform Spatio-Temporal sampling in a single pass/shader, operates on the last frame vs current+previous without",
        },
        {
            item = "EnableSeparateDenoising",
            name = "Enable Separate Denoising",
            category = "Editor/RTXDI",
            tooltip = "Denoise Indirect/Direct lighting seperately, quality improvement and fixes foilage lighting",
        },
        {
            item = "EnableRTXDIDenoising",
            name = "Enable DI Denoising",
            category = "Editor/RTXDI",
            tooltip = "Unknown but breaks DI with no performance difference when disabled",
        },
        {
            item = "EnableEnvironmentLights",
            name = "Enable Environmental Lights",
            category = "Editor/RTXDI",
            tooltip = "No visible impact",
        },
        {
            item = "UseCustomDenoiser",
            name = "Enable Custom Denoiser",
            category = "Editor/RTXDI",
            tooltip = "No visible impact (at least with ReLAX), costs performance",
        },
        {
            item = "InitialCandidatesInTemporal",
            name = "Initial Temporal Candidates",
            category = "Editor/RTXDI",
            tooltip = "Unknown, no visible/perf impact",
        },
        {
            item = "EnableGradients",
            name = "Enable Gradients",
            category = "Editor/RTXDI",
            tooltip = "Enables the computation of gradients for confidence pass in DI, aids performance",
        },
        {
            item = "EnableEmissiveTriangleLights",
            name = "Enable Emissive Triangle Lights",
            category = "Editor/RTXDI",
            tooltip = "Broken, breaks DI due to the exponential rise in light sources for sampling",
        },
        {
            item = "EnableAnalyticalLights",
            name = "Enable Analytical Lights",
            category = "Editor/RTXDI",
            tooltip = "Enables most light sources beyond sunlight",
        },
        {
            item = "EnableGlobalLight",
            name = "Enable Global Light",
            category = "Editor/RTXDI",
            tooltip = "Appears to be a higher radiance/quality sunlight path, notably boosts daylight visuals with unknown compatibility",
        },
        {
            item = "EnableEmissiveProxyLightRejection",
            name = "Enable Emissive Proxy Light Rejection",
            category = "Editor/RTXDI",
            tooltip = "Potential minor performance impact",
        },
        {
            item = "UseCSReusePasses",
            name = "Use CS Reuse Passes",
            category = "Editor/RTXDI",
            tooltip = "Unknown, CS is likely Computer Shaders",
        },
        {
            item = "AllowRTXDIRejitter",
            name = "AllowRTXDIRejitter",
            category = "Rendering",
            tooltip = "Unknown",
        },
        {
            item = "ForceAllShadows",
            name = "ForceAllShadows",
            category = "Editor/RTXDI",
            tooltip = "Unknown",
        },
        {
            item = "EnableAllEmissives",
            name = "EnableAllEmissives",
            category = "Editor/RTXDI",
            tooltip = "Unknown",
        },
        {
            item = "Debug_UpdateLightHits",
            name = "Debug_UpdateLightHits",
            category = "Editor/RTXDI",
            tooltip = "Unknown",
        },
        {
            item = "Debug_UpdateLightHits",
            name = "Debug_UpdateLightHits",
            category = "Editor/RTXDI",
            tooltip = "Unknown",
        },
        {
            item = "PTEnableDirectEmissives",
            name = "PTEnableDirectEmissives",
            category = "Editor/RTXDI",
            tooltip = "Unknown",
        },
        {
            item = "PTEnableDirectSkylight",
            name = "PTEnableDirectSkylight",
            category = "Editor/RTXDI",
            tooltip = "Unknown",
        },
    },

    RTXGI = {
        {
            item = "Enable",
            name = "Enable ReSTIR GI",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable ReSTIR GI indirect lighting, covers the bulk of indirect lighting paths when used with SHARC",
        },
        {
            item = "EnableFused",
            name = "Enable Fused Spatiotemporal GI (recommended)",
            category = "Editor/ReSTIRGI",
            tooltip = "Appears to be the only properly functioning GI pathway implemented, performs a spatiotemporal pass on the last frame, causes more ghosting/smearing",
        },
        {
            item = "EnableBoilingFilter",
            name = "Enable GI Boiling Filter",
            category = "Editor/ReSTIRGI",
            tooltip = "Reduces the weight of oversampled reservoirs to reduce bias",
        },
        {
            item = "UseTemporalRGS",
            name = "Enable Temporal Reuse",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable temporal pass in non-fused shaders, broken specular",
        },
        {
            item = "UseSpatialRGS",
            name = "Enable Spatial Reuse",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable spatial pass in non-fused shaders, broken everything (appears to be in debug mode half/half screen)",
        },
        {
            item = "EnableFallbackSampling",
            name = "Enable GI Fallback Sampling",
            category = "Editor/ReSTIRGI",
            tooltip = "Unknown, likely no impact in FUSED",
        },
    },


    REGIR = {
        {
            item = "Enable",
            name = "Enable ReGIR GI",
            category = "Editor/ReGIR",
            tooltip = "Enable use of ReGIR world-space light reservoir grid for Indirect (GI)",
        },
        {
            item = "UseForDI",
            name = "Enable ReGIR DI (requires GI)",
            category = "Editor/ReGIR",
            tooltip = "Extends use of ReGIR to Direct Lighting, feeding ReSTIR",
        },
    },


    RELAX = {
        {
            item = "VirtualHistoryClamping",
            name = "Virtual History Clamping (Direct)",
            category = "Editor/Denoising/ReLAX/Direct/Specular",
            tooltip = "Clamp history for Specular lighting (direct)",
        },
        {
            item = "VirtualHistoryClamping",
            name = "Virtual History Clamping (Indirect)",
            category = "Editor/Denoising/ReLAX/Indirect/Specular",
            tooltip = "Clamp history for Specular lighting (direct)",
        },
        {
            item = "AntiFirefly",
            name = "Anti Firefly (Direct)",
            category = "Editor/Denoising/ReLAX/Direct/Common",
            tooltip = "Attempt to filter out fireflies in Direct denoising",
        },
        {
            item = "AntiFirefly",
            name = "Anti Firefly (Indirect)",
            category = "Editor/Denoising/ReLAX/Indirect/Common",
            tooltip = "Attempt to filter out fireflies in Indirect denoising",
        },
        {
            item = "MaterialTest",
            name = "Material Test (Direct)",
            category = "Editor/Denoising/ReLAX/Direct/Diffuse",
            tooltip = "Attempt to filter out fireflies in Direct denoising",
        },
        {
            item = "MaterialTest",
            name = "Material Test (Indirect)",
            category = "Editor/Denoising/ReLAX/Indirect/Diffuse",
            tooltip = "Attempt to filter out fireflies in Indirect denoising",
        },
        {
            item = "MaterialTest",
            name = "Material Test (Direct S)",
            category = "Editor/Denoising/ReLAX/Direct/Specular",
            tooltip = "Attempt to filter out fireflies in Direct denoising",
        },
        {
            item = "MaterialTest",
            name = "Material Test (Indirect S)",
            category = "Editor/Denoising/ReLAX/Indirect/Specular",
            tooltip = "Attempt to filter out fireflies in Indirect denoising",
        },
        {
            item = "ReprojectionTestSkippingWithoutMotion",
            name = "Reprojection Test Skipping Without Motion (Direct)",
            category = "Editor/Denoising/ReLAX/Direct/Common",
            tooltip = "Reprojection Test Skipping Without Motion (Direct)",
        },
        {
            item = "ReprojectionTestSkippingWithoutMotion",
            name = "Reprojection Test Skipping Without Motion (Indirect)",
            category = "Editor/Denoising/ReLAX/Indirect/Common",
            tooltip = "Reprojection Test Skipping Without Motion (Indirect)",
        },
    },


    NRD = {
        {
            item = "UseReblurForDirectRadiance",
            name = "Use Reblur ForDirect Radiance",
            category = "RayTracing/NRD",
            tooltip = "Use Reblur ForDirect Radiance",
        },
        {
            item = "UseReblurForIndirectRadiance",
            name = "Use Reblur For Indirect Radiance",
            category = "RayTracing/NRD",
            tooltip = "Use Reblur For Indirect Radiance",
        },
        {
            item = "EnableReferenceCaptureParameters",
            name = "Enable Reference Capture Parameters",
            category = "Editor/Denoising/NRD",
            tooltip = "Allow Reference  Denoising for testing/comparison",
        },
        {
            item = "EnableReferenceAccumulation",
            name = "Enable Reference Accumulation",
            category = "RayTracing",
            tooltip = "Allow Reference Accumulation for testing/comparison",
        },
        {
            item = "EnableScalingCompensation",
            name = "Enable Scaling Compensation",
            category = "Editor/Denoising/NRD",
            tooltip = "Enable Scaling Compensation",
        },
    },

    RTOPTIONS = {
        {
            item = "EnableShadowCascades",
            name = "Enable Shadow Cascades",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "UseScreenSpaceData",
            name = "Enable Screen Space",
            category = "Editor/PathTracing",
            tooltip = "Unknown",
        },
        {
            item = "UseSSRFallback",
            name = "Use SSR Fallback",
            category = "Editor/PathTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableProbabilisticSampling",
            name = "Enable Probabilistic",
            category = "RayTracing/Reference",
            tooltip = "Unknown",
        },
        {
            item = "EnableLocalLights",
            name = "EnableLocalLights",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "AllowRayTracedReferenceRejitter",
            name = "AllowRayTracedReferenceRejitter",
            category = "Rendering",
            tooltip = "Unknown",
        },
        {
            item = "HitDistance",
            name = "Hit Distance Testing",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "RTXDIEnvMap",
            name = "Environmental Map",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "RTXDILocalLightPdf",
            name = "PDF - Local Light",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "RTXDIEnvMapPdf",
            name = "PDF - Environmental",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "SkyRadianceExposureScaling",
            name = "SkyRadianceExposureScaling",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableImportanceSampling",
            name = "EnableImportanceSampling",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableGlobalIllumination",
            name = "EnableGlobalIllumination",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableReflection",
            name = "EnableReflection",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableAmbientOcclusion",
            name = "EnableAmbientOcclusion",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableDiffuseIllumination",
            name = "EnableDiffuseIllumination",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableMirrorMaterialReflection",
            name = "EnableMirrorMaterialReflection",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableTransparentReflection",
            name = "EnableTransparentReflection",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableReferenceSER",
            name = "EnableReferenceSER",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableGlobalShadow",
            name = "EnableGlobalShadow",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableLocalShadow",
            name = "EnableLocalShadow",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableVisibilityCheck",
            name = "Enable Visibility Check",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "SkipClusteredProxies",
            name = "SkipClusteredProxies",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "EnableFixed",
            name = "EnableFixed",
            category = "RayTracing/Reference",
            tooltip = "Unknown",
        },
        {
            item = "RTXDIRIS",
            name = "RTXDIRIS",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "AdaptiveSampling",
            name = "Adaptive Sampling - Reflection",
            category = "RayTracing/Reflection",
            tooltip = "Unknown",
        },
        {
            item = "AdaptiveSampling",
            name = "Adaptive Sampling - Diffuse",
            category = "RayTracing/Diffuse",
            tooltip = "Unknown",
        },
        {
            item = "NrdInputs",
            name = "NrdInputs",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "GlobalShadow",
            name = "GlobalShadow",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "AmbientOcclusion",
            name = "AmbientOcclusion",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "DiffuseIllumination",
            name = "DiffuseIllumination",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "ReSTIRGI",
            name = "ReSTIRGI",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "ObjectMotion",
            name = "ObjectMotion",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "ShaderClock",
            name = "ShaderClock",
            category = "RayTracing/Debug",
            tooltip = "Unknown",
        },
        {
            item = "ForceShadowLODBiasUsage",
            name = "ForceShadowLODBiasUsage",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "EnableShadowOptimizations",
            name = "EnableShadowOptimizations",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "InstanceFlagDisableOMMS",
            name = "InstanceFlagDisableOMMS",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "AllowInstanceFlagDisableOMMS",
            name = "AllowInstanceFlagDisableOMMS",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "RTXDI",
            name = "RTXDI",
            category = "Developer/FeatureToggles",
            tooltip = "Unknown",
        },
        {
            item = "DLSSD",
            name = "DLSSD",
            category = "Developer/FeatureToggles",
            tooltip = "Unknown",
        },
        {
            item = "EnableNRD",
            name = "EnableNRD",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "UpdateUseHalfFloat",
            name = "UpdateUseHalfFloat",
            category = "RayTracing/DynamicInstance",
            tooltip = "Unknown",
        },
        {
            item = "UpdateUseBatching",
            name = "UpdateUseBatching",
            category = "RayTracing/DynamicInstance",
            tooltip = "Unknown",
        },
        {
            item = "CheckerboardGI",
            name = "CheckerboardGI",
            category = "Rendering",
            tooltip = "Unknown",
        },
        {
            item = "Enabled",
            name = "PT Interop Cache",
            category = "Interop/Cache",
            tooltip = "Unknown",
        },
        {
            item = "CharacterRimEnhancement",
            name = "Character Rim Enhancement",
            category = "Developer/FeatureToggles",
            tooltip = "Unknown",
        },
        {
            item = "AllowSkinAmbientMix",
            name = "AllowSkinAmbientMix",
            category = "Editor/Characters/Skin",
            tooltip = "Unknown",
        },
        {
            item = "EnableSkinning",
            name = "EnableSkinning",
            category = "RayTracing",
            tooltip = "Unknown",
        },
        {
            item = "UseSkinningLOD",
            name = "UseSkinningLOD",
            category = "Rendering",
            tooltip = "Unknown",
        },
        {
            item = "CharacterSubsurfaceStochastic",
            name = "CharacterSubsurfaceStochastic",
            category = "Developer/FeatureToggles",
            tooltip = "Unknown",
        },
        {
            item = "CharacterSubsurfaceScattering",
            name = "CharacterSubsurfaceScattering",
            category = "Developer/FeatureToggles",
            tooltip = "Unknown",
        },
        {
            item = "CharacterSubsurfaceTranslucency",
            name = "CharacterSubsurfaceTranslucency",
            category = "Developer/FeatureToggles",
            tooltip = "Unknown",
        },
        {
            item = "CharacterLightBlockers",
            name = "CharacterLightBlockers",
            category = "Developer/FeatureToggles",
            tooltip = "Unknown",
        },
        
    },

    SHARC = {
        {
            item = "Enable",
            name = "SHARC - Enable",
            category = "Editor/SHARC",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "UseRTXDI",
            name = "SHARC - UseRTXDI",
            category = "Editor/SHARC",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "UseRTXDIAtPrimary",
            name = "SHARC - UseRTXDIAtPrimary",
            category = "Editor/SHARC",
            tooltip = "Feed data from RTXDI at the first SHARC hit, optimisation",
        },
        {
            item = "UseRTXDIWithAlbedo",
            name = "SHARC - UseRTXDIWithAlbedo",
            category = "Editor/SHARC",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "UsePrevFrame",
            name = "SHARC - UsePrevFrame",
            category = "Editor/SHARC",
            tooltip = "Use data from the previous frame",
        },
        {
            item = "Debug",
            name = "Debug",
            category = "Editor/SHARC",
            tooltip = "Enables visualisation of SHARC cache",
        },
        {
            item = "Update",
            name = "Update",
            category = "Editor/SHARC",
            tooltip = "Required for SHARC functioning",
        },
        {
            item = "Resolve",
            name = "Resolve",
            category = "Editor/SHARC",
            tooltip = "Required for SHARC functioning",
        },
        {
            item = "Clear",
            name = "Clear",
            category = "Editor/SHARC",
            tooltip = "Clear SHARC cache each frame",
        },
        {
            item = "Step",
            name = "Step",
            category = "Editor/SHARC",
            tooltip = "Unknown",
        },
    },

    RTINT = {
        {
            item = "BiasCorrectionMode",
            name = "BiasCorrectionMode DI",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "EmissiveLOD",
            name = "DI Emissive LOD",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "NumInitialSamples",
            name = "DI NumInitialSamples",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "NumEnvMapSamples",
            name = "DI NumEnvMapSamples",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "SpatialNumSamples",
            name = "DI SpatialNumSamples",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "SpatialNumDisocclusionBoostSamples",
            name = "DI SpatialNumDisocclusionBoostSamples",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "MaxHistoryLength",
            name = "DI MaxHistoryLength",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "PermutationSamplingMode",
            name = "PermutationSamplingMode DI",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "BiasCorrectionMode",
            name = "BiasCorrectionMode GI",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "MaxHistoryLength",
            name = "MaxHistoryLength GI",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "TargetHistoryLength",
            name = "TargetHistoryLength GI",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "MaxReservoirAge",
            name = "MaxReservoirAge GI",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "PermutationSamplingMode",
            name = "PermutationSamplingMode GI",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "SpatialNumSamples",
            name = "SpatialNumSamples GI",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "SpatialNumDisocclusionBoostSamples",
            name = "SpatialNumDisocclusionBoostSamples GI",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "DownscaleFactor",
            name = "SHARC Downscale (LOG)",
            category = "Editor/SHARC",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "Bounces",
            name = "SHARC Bounces",
            category = "Editor/SHARC",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "HistoryReset",
            name = "SHARC HistoryReset",
            category = "Editor/SHARC",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "PrimaryRays",
            name = "PrimaryRays",
            category = "RayTracing/Debug",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "ImportanceSampling",
            name = "ImportanceSampling",
            category = "RayTracing/Debug",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "DebugMode",
            name = "DebugMode",
            category = "RayTracing",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "EnableAutomaticRotation",
            name = "TLAS EnableAutomaticRotation",
            category = "RayTracing/TLAS",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "InstanceFlagForceOMM2StateOnLODXAndAbove",
            name = "InstanceFlagForceOMM2StateOnLODXAndAbove",
            category = "RayTracing",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "ForceShadowLODBiasValue",
            name = "ForceShadowLODBiasValue",
            category = "RayTracing",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "Capacity",
            name = "LL Capacity",
            category = "RayTracing/LocalLight",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "GridSize",
            name = "LL GridSize",
            category = "RayTracing/LocalLight",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "BatchSize",
            name = "LL BatchSize",
            category = "RayTracing/LocalLight",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "ForceUpdate",
            name = "ForceUpdate",
            category = "RayTracing/Debug",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "WorkingSetTimeout",
            name = "WorkingSetTimeout",
            category = "RayTracing/BlasCache",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "RefitNumMax",
            name = "RefitNumMax",
            category = "RayTracing/DynamicInstance",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "BounceNumber",
            name = "BounceNumber",
            category = "RayTracing/Reference",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "RayNumber",
            name = "RayNumber",
            category = "RayTracing/Reference",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "ShadingCandidatesCount",
            name = "ShadingCandidatesCount",
            category = "Editor/ReGIR",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "BuildCandidatesCount",
            name = "BuildCandidatesCount",
            category = "Editor/ReGIR",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "LightSlotsCount",
            name = "LightSlotsCount",
            category = "Editor/ReGIR",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "EmissiveLightCount",
            name = "EmissiveLightCount",
            category = "RTXDI",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "AnalyticLightCount",
            name = "AnalyticLightCount",
            category = "RTXDI",
            tooltip = "Feed data from RTXDI, optimisation",
        },
    },

    RTFLOAT = {
        {
            item = "ClipRadius",
            name = "LL ClipRadius",
            category = "RayTracing/LocalLight",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "SpatialSamplingRadius",
            name = "DI SpatialSamplingRadius",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "EmissiveProxyLightRejectionDistance",
            name = "DI EmissiveProxyLightRejectionDistance",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "ShadowFadeFraction",
            name = "DI ShadowFadeFraction",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "ForcedShadowLightSourceRadius",
            name = "DI ForcedShadowLightSourceRadius",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "MaxIntensity",
            name = "DI MaxIntensity",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "EmissiveDistanceThreshold",
            name = "DI EmissiveDistanceThreshold",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "BoilingFilterStrength",
            name = "DI BoilingFilterStrength",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "BoilingFilterStrength",
            name = "GI BoilingFilterStrength",
            category = "Editor/RTXDI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "SpatialSamplingRadius",
            name = "GI SpatialSamplingRadius",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "BoilingFilterStrength",
            name = "GI BoilingFilterStrength",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "TracingRadius",
            name = "TracingRadius",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "TracingRadiusReflections",
            name = "TracingRadiusReflections",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "RayNormalOffset",
            name = "RayNormalOffset",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "RayViewOffset",
            name = "RayViewOffset",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "SunAngularSize",
            name = "SunAngularSize",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "SunScatteringScale",
            name = "SunScatteringScale",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "ImportanceSamplingTransitionMin",
            name = "ImportanceSamplingTransitionMin",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "ImportanceSamplingTransitionMax",
            name = "ImportanceSamplingTransitionMax",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "CullingDistanceCharacter",
            name = "CullingDistanceCharacter",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "CullingDistanceVehicle",
            name = "CullingDistanceVehicle",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "LightVolumeBoundaryExtension",
            name = "LightVolumeBoundaryExtension",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "EmissiveClipRadius",
            name = "EmissiveClipRadius",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "EmissiveRangeScale",
            name = "EmissiveRangeScale",
            category = "RayTracing",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "VisibilityFrustumOffset",
            name = "VisibilityFrustumOffset",
            category = "RayTracing/Collector",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "VisibilityCullingRadius",
            name = "VisibilityCullingRadius",
            category = "RayTracing/Collector",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "LocalShadowCullingRadius",
            name = "LocalShadowCullingRadius",
            category = "RayTracing/Collector",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
    },
}

return options
