-- options.lua

local options = {
    Tweaks = {
--[[        {
            item = "turboHack",
            name = "Enable PT Turbo (slightly reduce quality outdoors)",
            category = "internal",
            tooltip = "RTXDI spatial sampling is mostly needed indoors. This tweak reduces it while\noutdoors to try and maintain FPS in complex outdoor areas. It CAN reduce\nvisual quality outdoors in certain situations (white cars\nand highly reflective surfaces in particular).",
        },
        {
            item = "rainFix",
            name = "Enable PT Rain Fix",
            category = "internal",
            tooltip = "Enables full particle integration with path tracing while it's not raining\nor you're indoors." },]]
        {
            item = "DLSS_D",
            name = "Enable PT Denoiser: Ray Reconstruction",
            category = "/graphics/presets",
            tooltip = "Ultra+ allows the engine to override this avoid crashes, so this option will\nappear not to save (Default: N/A)",
        },
        {
            item = "EnableNRD",
            name = "Enable PT Denoiser: NRD",
            category = "RayTracing",
            tooltip = "NRD is only intended when NOT using ray reconstruction (for example AMD).\nThe engine tries to turn this on under certain circumstances, Ultra+ Control\nwill try and show you if it has become enabled, though there may be a bug in\nCP 2.1x that causes NRD to become partionally enabled (see the above PT21\nFPS Fix).",
        },
        {
            item = "EnableRIS",
            name = "Enable resampled importance sampling (RIS)",
            category = "RayTracing/Reference",
            tooltip = "RIS is resampled importance sampling. Disable this if you use reLIGHT\n(Default: On)",
        },
        {
            item = "Enable",
            name = "Enable SHaRC Bounce Cache",
            category = "Editor/SHARC",
            tooltip = "(Default: On)",
        },
        {
            item = "EnableGradients",
            name = "Enable RTXDI Gradients",
            category = "Editor/RTXDI",
            tooltip = "(Default: Off)",
        },
        {
            item = "EnableSeparateDenoising",
            name = "Enable RTXDI Separate Denoising",
            category = "Editor/RTXDI",
            tooltip = "NOTE: With RR disabled, you may need to untick this\nand reload for now for NRD to work correctly (Default: On)",
        },
    },
    Features = {
        {
            item = "Bloom",
            name = "Enable Bloom",
            category = "Developer/FeatureToggles",
            tooltip = "(Default: On)",
        },
        {
            item = "Distortion",
            name = "Enable Distortion Effects",
            category = "Developer/FeatureToggles",
            tooltip = "(Default: On)",
        },
        {
            item = "ScreenSpaceHeatHaze",
            name = "Enable Heat Haze Effects",
            category = "Developer/FeatureToggles",
            tooltip = "Can distort badly with path tracing (Default: On)",
        },
        {
            item = "UseScreenSpaceData",
            name = "Enable Blended Screen Space Reflections",
            category = "Editor/PathTracing",
            tooltip = "Blends screenspace reflections with RT or PT reflections (less physically-based)\nbut fixes some missing reflections.",
        },
        {
            item = "VolumetricFog",
            name = "Enable Volumetric Fog",
            category = "Developer/FeatureToggles",
            tooltip = "",
        },
        {
            item = "DistantVolFog",
            name = "Enable Distant Volumetric Fog",
            category = "Developer/FeatureToggles",
            tooltip = "Can be less obvious depending on which weather env you're using (Default: On)",
        },
        {
            item = "DistantFog",
            name = "Enable Distant Raster Fog",
            category = "Developer/FeatureToggles",
            tooltip = "Makes buildings and mountains fade into the atmosphere (Default: On)",
        },
        {
            item = "DistantGI",
            name = "Enable Distant Global Illumination",
            category = "Developer/FeatureToggles",
            tooltip = "(Default: On)",
        },
        {
            item = "DistantShadows",
            name = "Enable Distant Shadows",
            category = "Developer/FeatureToggles",
            tooltip = "(Default: On)",
        },
        {
            item = "HideFPPAvatar",
            name = "Disable Player Reflection (except head)",
            category = "RayTracing",
            tooltip = "If unchecked this will show your player character in reflections, except for\ntheir head, unfortunately (Default: Off)",
        },
        {
            item = "CharacterRimEnhancement",
            name = "Enable Object and NPC Rim Enhancement",
            category = "Developer/FeatureToggles",
            tooltip = "Only works in raster and RT modes (Default: On)",
        },
        {
            item = "EnableCustomMipBias",
            name = "Force INI Mip Bias",
            category = "Editor/MipBias",
            tooltip = "Caution: Not recommended for 12GB VRAM or less (Default: Off)",
        },
    },
    RTXDI = {
        {
            item = "EnableLocalLightImportanceSampling",
            name = "Local-Light Importance Sampling (LLIS)",
            category = "Editor/RTXDI",
            tooltip = "Prioritise Local Light sources when sampling the image, implementation appears problematic",
        },
        {
            item = "EnableFallbackLight",
            name = "Fallback Lighting",
            category = "Editor/RTXDI",
            tooltip = "Use a fallback light when sampling is insufficient, may introduce bias but aids with LLIS",
        },
        {
            item = "EnableApproximateTargetPDF",
            name = "Approximate Target PDF",
            category = "Editor/RTXDI",
            tooltip = "Unknown impact, found it reduced performance for no reasonable quality gain",
        },
        {
            item = "UseFusedApproach",
            name = "Enable Fused Spatiotemporal DI",
            category = "Editor/RTXDI",
            tooltip = "Perform Spatio-Temporal sampling in a single pass/shader, operates on the last frame vs current+previous without",
        },
        {
            item = "EnableSeparateDenoising",
            name = "Enable Separate Denoising",
            category = "Editor/RTXDI",
            tooltip = "Denoise Indirect/Direct lighting seperately, quality improvement and fixes foilage lighting",
        },
        {
            item = "EnableRTXDIDenoising",
            name = "Enable DI Denoising",
            category = "Editor/RTXDI",
            tooltip = "Unknown but breaks DI with no performance difference when disabled",
        },
        {
            item = "EnableEnvironmentLights",
            name = "Enable Environmental Lights",
            category = "Editor/RTXDI",
            tooltip = "No visible impact",
        },
        {
            item = "UseCustomDenoiser",
            name = "Enable Custom Denoiser",
            category = "Editor/RTXDI",
            tooltip = "No visible impact (at least with ReLAX), costs performance",
        },
        {
            item = "InitialCandidatesInTemporal",
            name = "Initial Temporal Candidates",
            category = "Editor/RTXDI",
            tooltip = "Unknown, no visible/perf impact",
        },
        {
            item = "EnableGradients",
            name = "Enable Gradients",
            category = "Editor/RTXDI",
            tooltip = "Enables the computation of gradients for confidence pass in DI, aids performance",
        },
        {
            item = "EnableEmissiveTriangleLights",
            name = "Enable Emissive Triangle Lights",
            category = "Editor/RTXDI",
            tooltip = "Broken, breaks DI due to the exponential rise in light sources for sampling",
        },
        {
            item = "EnableAnalyticalLights",
            name = "Enable Analytical Lights",
            category = "Editor/RTXDI",
            tooltip = "Enables most light sources beyond sunlight",
        },
        {
            item = "EnableGlobalLight",
            name = "Enable Global Light",
            category = "Editor/RTXDI",
            tooltip = "Appears to be a higher radiance/quality sunlight path, notably boosts daylight visuals with unknown compatibility",
        },
        {
            item = "UseCSReusePasses",
            name = "Use CS Reuse Passes",
            category = "Editor/RTXDI",
            tooltip = "Unknown, CS is likely Computer Shaders",
        },
        {
            item = "AllowRTXDIRejitter",
            name = "Allow RTXDI Rejitter",
            category = "Rendering",
            tooltip = "RTXDI jtter information is destroyed by the RTXDI denoiser. Collect and pass jitter information through the temporal upscaler as a workaround to preserve detail",
        },
        {
            item = "ForceAllShadows",
            name = "ForceAllShadows",
            category = "Editor/RTXDI",
            tooltip = "Forces shadows from meshes not in the PT world space to be traced",
        },
        {
            item = "EnableAllEmissives",
            name = "EnableAllEmissives",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "Debug_UpdateLightHits",
            name = "Debug_UpdateLightHits",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "PTEnableDirectEmissives",
            name = "PTEnableDirectEmissives",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "PTEnableDirectSkylight",
            name = "PTEnableDirectSkylight",
            category = "Editor/RTXDI",
            tooltip = "",
        },
    },
    RTXGI = {
        {
            item = "Enable",
            name = "Enable ReSTIR GI",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable ReSTIR GI indirect lighting, covers the bulk of indirect lighting paths when used with SHARC",
        },
        {
            item = "EnableFused",
            name = "Enable Fused Spatiotemporal GI (recommended)",
            category = "Editor/ReSTIRGI",
            tooltip = "Appears to be the only properly functioning GI pathway implemented, performs a spatiotemporal pass on the last frame, causes more ghosting/smearing",
        },
        {
            item = "EnableBoilingFilter",
            name = "Enable GI Boiling Filter",
            category = "Editor/ReSTIRGI",
            tooltip = "Reduces the weight of oversampled reservoirs to reduce bias",
        },
        {
            item = "UseTemporalRGS",
            name = "Enable Temporal Reuse",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable temporal pass in non-fused shaders, broken specular",
        },
        {
            item = "UseSpatialRGS",
            name = "Enable Spatial Reuse",
            category = "Editor/ReSTIRGI",
            tooltip = "Enable spatial pass in non-fused shaders, broken everything (appears to be in debug mode half/half screen)",
        },
        {
            item = "EnableFallbackSampling",
            name = "Enable GI Fallback Sampling",
            category = "Editor/ReSTIRGI",
            tooltip = "Unknown, likely no impact in FUSED",
        },
    },
    REGIR = {
        {
            item = "Enable",
            name = "Enable ReGIR GI",
            category = "Editor/ReGIR",
            tooltip = "Enable use of ReGIR world-space light reservoir grid for Indirect (GI)",
        },
        {
            item = "UseForDI",
            name = "Enable ReGIR DI (requires GI)",
            category = "Editor/ReGIR",
            tooltip = "Extends use of ReGIR to Direct Lighting, feeding ReSTIR",
        },
    },
    RELAX = {
        {
            item = "VirtualHistoryClamping",
            name = "Virtual History Clamping (Direct)",
            category = "Editor/Denoising/ReLAX/Direct/Specular",
            tooltip = "Clamp history for Specular lighting (direct)",
        },
        {
            item = "VirtualHistoryClamping",
            name = "Virtual History Clamping (Indirect)",
            category = "Editor/Denoising/ReLAX/Indirect/Specular",
            tooltip = "Clamp history for Specular lighting (direct)",
        },
        {
            item = "AntiFirefly",
            name = "Anti Firefly (Direct)",
            category = "Editor/Denoising/ReLAX/Direct/Common",
            tooltip = "Attempt to filter out fireflies in Direct denoising",
        },
        {
            item = "AntiFirefly",
            name = "Anti Firefly (Indirect)",
            category = "Editor/Denoising/ReLAX/Indirect/Common",
            tooltip = "Attempt to filter out fireflies in Indirect denoising",
        },
        {
            item = "MaterialTest",
            name = "Material Test (Direct)",
            category = "Editor/Denoising/ReLAX/Direct/Diffuse",
            tooltip = "",
        },
        {
            item = "MaterialTest",
            name = "Material Test (Indirect)",
            category = "Editor/Denoising/ReLAX/Indirect/Diffuse",
            tooltip = "",
        },
        {
            item = "MaterialTest",
            name = "Material Test (Direct S)",
            category = "Editor/Denoising/ReLAX/Direct/Specular",
            tooltip = "",
        },
        {
            item = "MaterialTest",
            name = "Material Test (Indirect S)",
            category = "Editor/Denoising/ReLAX/Indirect/Specular",
            tooltip = "",
        },
        {
            item = "ReprojectionTestSkippingWithoutMotion",
            name = "Reprojection Test Skipping Without Motion (Direct)",
            category = "Editor/Denoising/ReLAX/Direct/Common",
            tooltip = "",
        },
        {
            item = "ReprojectionTestSkippingWithoutMotion",
            name = "Reprojection Test Skipping Without Motion (Indirect)",
            category = "Editor/Denoising/ReLAX/Indirect/Common",
            tooltip = "",
        },
    },
    NRD = {
        {
            item = "UseReblurForDirectRadiance",
            name = "Use Reblur ForDirect Radiance",
            category = "RayTracing/NRD",
            tooltip = "Use Reblur ForDirect Radiance",
        },
        {
            item = "UseReblurForIndirectRadiance",
            name = "Use Reblur For Indirect Radiance",
            category = "RayTracing/NRD",
            tooltip = "Use Reblur For Indirect Radiance",
        },
        {
            item = "EnableReferenceCaptureParameters",
            name = "Enable Reference Capture Parameters",
            category = "Editor/Denoising/NRD",
            tooltip = "Allow Reference  Denoising for testing/comparison",
        },
        {
            item = "EnableReferenceAccumulation",
            name = "Enable Reference Accumulation",
            category = "RayTracing",
            tooltip = "Allow Reference Accumulation for testing/comparison",
        },
        {
            item = "EnableScalingCompensation",
            name = "Enable Scaling Compensation",
            category = "Editor/Denoising/NRD",
            tooltip = "Enable Scaling Compensation",
        },
    },
    RTOPTIONS = {
        {
            item = "EnableShadowCascades",
            name = "Enable Shadow Cascades",
            category = "RayTracing",
            tooltip = "Normally CP renders cascade shadows as raster. This forces them to be traced",
        },
        {
            item = "UseSSRFallback",
            name = "Use SSR Fallback",
            category = "Editor/PathTracing",
            tooltip = "Uses screenspace for rough reflections in PT, as a performance optimisation",
        },
        {
            item = "EnableProbabilisticSampling",
            name = "Enable Probabilistic Sampling",
            category = "RayTracing/Reference",
            tooltip = "Intelligently decides where to allocate PT rays, so ray count can be reduced",
        },
        {
            item = "EnableLocalLights",
            name = "Enable Local Lights",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "AllowRayTracedReferenceRejitter",
            name = "Allow NRD Rejitter",
            category = "Rendering",
            tooltip = "NRD jitter information is destroyed by the NRD denoiser. Collect and pass jitter information through the temporal upscaler as a workaround to preserve detail",
        },
        {
            item = "HitDistance",
            name = "Hit Distance Testing",
            category = "RayTracing/Debug",
            tooltip = "",
        },
        {
            item = "RTXDIEnvMap",
            name = "Environmental Map",
            category = "RayTracing/Debug",
            tooltip = "Enable the RTXDI environment map. However envmap is enabled/disabled depending on the mode (i.e. this CVar does nothing)",
        },
        {
            item = "RTXDILocalLightPdf",
            name = "PDF - Local Light",
            category = "RayTracing/Debug",
            tooltip = "Enable the RTXDI PDF for local lights. However PDF is enabled/disabled depending on the mode (i.e. this CVar does nothing)",
        },
        {
            item = "RTXDIEnvMapPdf",
            name = "PDF - Environmental",
            category = "RayTracing/Debug",
            tooltip = "Enable the RTXDI PDF for environmental lights. However PDF is enabled/disabled depending on the mode (i.e. this CVar does nothing)",
        },
        {
            item = "SkyRadianceExposureScaling",
            name = "Sky Radiance Exposure Scaling",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EnableImportanceSampling",
            name = "Enable Importance Sampling",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EnableGlobalIllumination",
            name = "Enable Global Illumination",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EnableReflection",
            name = "Enable Reflection",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EnableAmbientOcclusion",
            name = "Enable Ambient Occlusion",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EnableDiffuseIllumination",
            name = "Enable Diffuse Illumination",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EnableMirrorMaterialReflection",
            name = "Enable Mirror Material Reflection",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EnableTransparentReflection",
            name = "Enable Transparent Reflection",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EnableGlobalShadow",
            name = "Enable Global Shadow",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EnableLocalShadow",
            name = "Enable Local Shadow",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EnableVisibilityCheck",
            name = "Enable Visibility Check",
            category = "RayTracing/Debug",
            tooltip = "",
        },
        {
            item = "SkipClusteredProxies",
            name = "Skip Clustered Proxies",
            category = "RayTracing/Debug",
            tooltip = "",
        },
        {
            item = "EnableFixed",
            name = "Enable NRD Fixed",
            category = "RayTracing/Reference",
            tooltip = "",
        },
        {
            item = "RTXDIRIS",
            name = "Debug RTXDIRIS",
            category = "RayTracing/Debug",
            tooltip = "",
        },
        {
            item = "AdaptiveSampling",
            name = "Adaptive Sampling (Reflection)",
            category = "RayTracing/Reflection",
            tooltip = "",
        },
        {
            item = "AdaptiveSampling",
            name = "Adaptive Sampling (Diffuse)",
            category = "RayTracing/Diffuse",
            tooltip = "",
        },
        {
            item = "NrdInputs",
            name = "Debug NRD Inputs",
            category = "RayTracing/Debug",
            tooltip = "",
        },
        {
            item = "GlobalShadow",
            name = "Debug Global Shadow",
            category = "RayTracing/Debug",
            tooltip = "",
        },
        {
            item = "AmbientOcclusion",
            name = "Debug Ambient Occlusion",
            category = "RayTracing/Debug",
            tooltip = "",
        },
        {
            item = "DiffuseIllumination",
            name = "Debug Diffuse Illumination",
            category = "RayTracing/Debug",
            tooltip = "",
        },
        {
            item = "ReSTIRGI",
            name = "Debug ReSTIRGI",
            category = "RayTracing/Debug",
            tooltip = "",
        },
        {
            item = "ObjectMotion",
            name = "Debug Object Motion",
            category = "RayTracing/Debug",
            tooltip = "",
        },
        {
            item = "ShaderClock",
            name = "ShaderClock",
            category = "RayTracing/Debug",
            tooltip = "",
        },
        {
            item = "ForceShadowLODBiasUsage",
            name = "ForceShadowLODBiasUsage",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EnableShadowOptimizations",
            name = "EnableShadowOptimizations",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "InstanceFlagDisableOMMS",
            name = "Instance Flag Disable OMMS",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "AllowInstanceFlagDisableOMMS",
            name = "Allow Instance Flag Disable OMMS",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "RTXDI",
            name = "Enable RTXDI",
            category = "Developer/FeatureToggles",
            tooltip = "",
        },
        {
            item = "DLSSD",
            name = "Enable DLSSD (CTD warning)",
            category = "Developer/FeatureToggles",
            tooltip = "",
        },
        {
            item = "UpdateUseHalfFloat",
            name = "Update UseHalf Float",
            category = "RayTracing/DynamicInstance",
            tooltip = "Saves memory for floats that don't require double precision",
        },
        {
            item = "UpdateUseBatching",
            name = "Update Use Batching",
            category = "RayTracing/DynamicInstance",
            tooltip = "",
        },
        {
            item = "CheckerboardGI",
            name = "Checkerboard Global Illumination",
            category = "Rendering",
            tooltip = "Checkerboard the GI tracing as a performance optimisation. Default is 50% checkerboard and this can be reduced further below",
        },
        {
            item = "Enabled",
            name = "PT Interop Cache",
            category = "Interop/Cache",
            tooltip = "",
        },
        {
            item = "AllowSkinAmbientMix",
            name = "Allow Skin Ambient Mix",
            category = "Editor/Characters/Skin",
            tooltip = "Skin ambient light blending is broken in ray tracing. Ultra+ disables for this reason",
        },
        {
            item = "EnableSkinning",
            name = "EnableSkinning",
            category = "RayTracing",
            tooltip = "Generally this means materials skinning",
        },
        {
            item = "UseSkinningLOD",
            name = "UseSkinningLOD",
            category = "Rendering",
            tooltip = "This may mean - Use LODs specified in the materials",
        },
        {
            item = "CharacterSubsurfaceStochastic",
            name = "Character Subsurface Stochastic",
            category = "Developer/FeatureToggles",
            tooltip = "",
        },
        {
            item = "CharacterSubsurfaceScattering",
            name = "Character Subsurface Scattering",
            category = "Developer/FeatureToggles",
            tooltip = "",
        },
        {
            item = "CharacterSubsurfaceTranslucency",
            name = "Character Subsurface Translucency",
            category = "Developer/FeatureToggles",
            tooltip = "",
        },
        {
            item = "CharacterLightBlockers",
            name = "Character Light Blockers (CTD warning)",
            category = "Developer/FeatureToggles",
            tooltip = "",
        },
    },
    SHARC = {
        {
            item = "Enable",
            name = "SHARC - Enable",
            category = "Editor/SHARC",
            tooltip = "Enable use of SHARC cache for indirect lighting, accelerating indirect lighting and improving path tracing results",
        },
        {
            item = "UseRTXDI",
            name = "SHARC - UseRTXDI",
            category = "Editor/SHARC",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "UseRTXDIAtPrimary",
            name = "SHARC - UseRTXDIAtPrimary",
            category = "Editor/SHARC",
            tooltip = "Feed data from RTXDI at the first SHARC hit, optimisation",
        },
        {
            item = "UseRTXDIWithAlbedo",
            name = "SHARC - UseRTXDIWithAlbedo",
            category = "Editor/SHARC",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "UsePrevFrame",
            name = "SHARC - UsePrevFrame",
            category = "Editor/SHARC",
            tooltip = "Use data from the previous frame",
        },
        {
            item = "Debug",
            name = "Debug",
            category = "Editor/SHARC",
            tooltip = "Enables visualisation of SHARC cache",
        },
        {
            item = "Update",
            name = "Update",
            category = "Editor/SHARC",
            tooltip = "Required for SHARC functioning",
        },
        {
            item = "Resolve",
            name = "Resolve",
            category = "Editor/SHARC",
            tooltip = "Required for SHARC functioning",
        },
        {
            item = "Clear",
            name = "Clear",
            category = "Editor/SHARC",
            tooltip = "Clear SHARC cache each frame",
        },
        {
            item = "Step",
            name = "Step",
            category = "Editor/SHARC",
            tooltip = "",
        },
    },
    RTINT = {
        {
            item = "MaxFastAccumulatedFrameNum",
            name = "ReLAX Direct Diffuse Fast",
            category = "Editor/Denoising/ReLAX/Direct/Diffuse",
            tooltip = "",
        },
        {
            item = "MaxFastAccumulatedFrameNum",
            name = "ReLAX Indirect Diffuse Fast",
            category = "Editor/Denoising/ReLAX/Indirect/Diffuse",
            tooltip = "",
        },
        {
            item = "MaxFastAccumulatedFrameNum",
            name = "ReLAX Direct Specular Fast",
            category = "Editor/Denoising/ReLAX/Direct/Specular",
            tooltip = "",
        },
        {
            item = "MaxFastAccumulatedFrameNum",
            name = "ReLAX Indirect Specular Fast",
            category = "Editor/Denoising/ReLAX/Indirect/Specular",
            tooltip = "",
        },
        {
            item = "BiasCorrectionMode",
            name = "BiasCorrectionMode DI",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "EmissiveLOD",
            name = "DI Emissive LOD",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "NumInitialSamples",
            name = "DI NumInitialSamples",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "NumEnvMapSamples",
            name = "DI NumEnvMapSamples",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "SpatialNumSamples",
            name = "DI SpatialNumSamples",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "SpatialNumDisocclusionBoostSamples",
            name = "DI SpatialNumDisocclusionBoostSamples",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "MaxHistoryLength",
            name = "DI MaxHistoryLength",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "PermutationSamplingMode",
            name = "PermutationSamplingMode DI",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "BiasCorrectionMode",
            name = "BiasCorrectionMode GI",
            category = "Editor/ReSTIRGI",
            tooltip = "",
        },
        {
            item = "MaxHistoryLength",
            name = "MaxHistoryLength GI",
            category = "Editor/ReSTIRGI",
            tooltip = "",
        },
        {
            item = "TargetHistoryLength",
            name = "TargetHistoryLength GI",
            category = "Editor/ReSTIRGI",
            tooltip = "",
        },
        {
            item = "MaxReservoirAge",
            name = "MaxReservoirAge GI",
            category = "Editor/ReSTIRGI",
            tooltip = "",
        },
        {
            item = "PermutationSamplingMode",
            name = "PermutationSamplingMode GI",
            category = "Editor/ReSTIRGI",
            tooltip = "",
        },
        {
            item = "SpatialNumSamples",
            name = "SpatialNumSamples GI",
            category = "Editor/ReSTIRGI",
            tooltip = "",
        },
        {
            item = "SpatialNumDisocclusionBoostSamples",
            name = "SpatialNumDisocclusionBoostSamples GI",
            category = "Editor/ReSTIRGI",
            tooltip = "",
        },
        {
            item = "DownscaleFactor",
            name = "SHARC Downscale (LOG)",
            category = "Editor/SHARC",
            tooltip = "",
        },
        {
            item = "Bounces",
            name = "SHARC Bounces",
            category = "Editor/SHARC",
            tooltip = "",
        },
        {
            item = "HistoryReset",
            name = "SHARC HistoryReset",
            category = "Editor/SHARC",
            tooltip = "",
        },
        {
            item = "PrimaryRays",
            name = "PrimaryRays",
            category = "RayTracing/Debug",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "ImportanceSampling",
            name = "ImportanceSampling",
            category = "RayTracing/Debug",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "DebugMode",
            name = "DebugMode",
            category = "RayTracing",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "EnableAutomaticRotation",
            name = "TLAS EnableAutomaticRotation",
            category = "RayTracing/TLAS",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "InstanceFlagForceOMM2StateOnLODXAndAbove",
            name = "InstanceFlagForceOMM2StateOnLODXAndAbove",
            category = "RayTracing",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "ForceShadowLODBiasValue",
            name = "ForceShadowLODBiasValue",
            category = "RayTracing",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "Capacity",
            name = "LL Capacity",
            category = "RayTracing/LocalLight",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "GridSize",
            name = "LL GridSize",
            category = "RayTracing/LocalLight",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "BatchSize",
            name = "LL BatchSize",
            category = "RayTracing/LocalLight",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "ForceUpdate",
            name = "ForceUpdate",
            category = "RayTracing/Debug",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "WorkingSetTimeout",
            name = "WorkingSetTimeout",
            category = "RayTracing/BlasCache",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "RefitNumMax",
            name = "RefitNumMax",
            category = "RayTracing/DynamicInstance",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "BounceNumber",
            name = "BounceNumber",
            category = "RayTracing/Reference",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "RayNumber",
            name = "RayNumber",
            category = "RayTracing/Reference",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "ShadingCandidatesCount",
            name = "ShadingCandidatesCount",
            category = "Editor/ReGIR",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "BuildCandidatesCount",
            name = "BuildCandidatesCount",
            category = "Editor/ReGIR",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "LightSlotsCount",
            name = "LightSlotsCount",
            category = "Editor/ReGIR",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "SpatialVarianceEstimationHistoryThreshold",
            name = "SpatialVarianceEstimationHistoryThreshold DI",
            category = "Editor/Denoising/ReLAX/Direct/Common",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "SpatialVarianceEstimationHistoryThreshold",
            name = "SpatialVarianceEstimationHistoryThreshold GI",
            category = "Editor/Denoising/ReLAX/Indirect/Common",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "HistoryFixFrameNum",
            name = "HistoryFixFrameNum DI",
            category = "Editor/Denoising/ReLAX/Direct/Common",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "HistoryFixFrameNum",
            name = "HistoryFixFrameNum GI",
            category = "Editor/Denoising/ReLAX/Indirect/Common",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "EmissiveLightCount",
            name = "EmissiveLightCount",
            category = "RTXDI",
            tooltip = "Feed data from RTXDI, optimisation",
        },
        {
            item = "AnalyticLightCount",
            name = "AnalyticLightCount",
            category = "RTXDI",
            tooltip = "Feed data from RTXDI, optimisation",
        },
    },
    RTFLOAT = {
        {
            item = "ClipRadius",
            name = "LL ClipRadius",
            category = "RayTracing/LocalLight",
            tooltip = "",
        },
        {
            item = "SpatialSamplingRadius",
            name = "DI SpatialSamplingRadius",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "EmissiveProxyLightRejectionDistance",
            name = "DI EmissiveProxyLightRejectionDistance",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "ShadowFadeFraction",
            name = "DI ShadowFadeFraction",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "ForcedShadowLightSourceRadius",
            name = "DI ForcedShadowLightSourceRadius",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "MaxIntensity",
            name = "DI MaxIntensity",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "EmissiveDistanceThreshold",
            name = "DI EmissiveDistanceThreshold",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "BoilingFilterStrength",
            name = "DI BoilingFilterStrength",
            category = "Editor/RTXDI",
            tooltip = "",
        },
        {
            item = "SpatialSamplingRadius",
            name = "GI SpatialSamplingRadius",
            category = "Editor/ReSTIRGI",
            tooltip = "",
        },
        {
            item = "BoilingFilterStrength",
            name = "GI BoilingFilterStrength",
            category = "Editor/ReSTIRGI",
            tooltip = "",
        },
        {
            item = "TracingRadius",
            name = "TracingRadius",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "TracingRadiusReflections",
            name = "TracingRadiusReflections",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "RayNormalOffset",
            name = "RayNormalOffset",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "RayViewOffset",
            name = "RayViewOffset",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "SunAngularSize",
            name = "SunAngularSize",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "SunScatteringScale",
            name = "SunScatteringScale",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "ImportanceSamplingTransitionMin",
            name = "ImportanceSamplingTransitionMin",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "ImportanceSamplingTransitionMax",
            name = "ImportanceSamplingTransitionMax",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "CullingDistanceCharacter",
            name = "CullingDistanceCharacter",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "CullingDistanceVehicle",
            name = "CullingDistanceVehicle",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "LightVolumeBoundaryExtension",
            name = "LightVolumeBoundaryExtension",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EmissiveClipRadius",
            name = "EmissiveClipRadius",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "EmissiveRangeScale",
            name = "EmissiveRangeScale",
            category = "RayTracing",
            tooltip = "",
        },
        {
            item = "VisibilityFrustumOffset",
            name = "VisibilityFrustumOffset",
            category = "RayTracing/Collector",
            tooltip = "",
        },
        {
            item = "VisibilityCullingRadius",
            name = "VisibilityCullingRadius",
            category = "RayTracing/Collector",
            tooltip = "",
        },
        {
            item = "LocalShadowCullingRadius",
            name = "LocalShadowCullingRadius",
            category = "RayTracing/Collector",
            tooltip = "",
        },
    },
}

return options
